platform :ios, '10.0'

target 'mpapp' do
  use_frameworks!

  # Pods for mpapp
  pod 'RealmSwift'
  pod 'RxRealm'
  pod "Resolver"
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod "RealmGeoQueries"

  target 'mpappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mpappUITests' do
    # Pods for testing
  end

end
