platform :ios, '10.0'

target 'mpapp' do
  use_frameworks!

  # Pods for mpapp
  pod 'RealmSwift'
  pod 'RxRealm'
  pod "Resolver"
  pod "PromiseKit"
  pod 'Alamofire', '~> 5.2'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '6.0.9'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'Firebase/Auth'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
  pod "RealmGeoQueries"

  target 'mpappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mpappUITests' do
    # Pods for testing
  end

end
