platform :ios, '10.0'

target 'mpapp' do
  use_frameworks!

  # Pods for mpapp
  pod 'RealmSwift'
  pod 'RxRealm'
  pod "Resolver"
  pod 'Gloss'
  pod "PromiseKit"
  pod 'Alamofire', '~> 5.2'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '5.2.0'
  pod 'GoogleMaps'
  pod 'GooglePlaces'

  target 'mpappTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'mpappUITests' do
    # Pods for testing
  end

end
